---
AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for AI content generators - Entry Info and Example Sentence Lambda functions

Parameters:
  CodeS3Bucket:
    Type: String
    Description: S3 bucket containing the Lambda function code ZIP file
  CodeS3Key:
    Type: String
    Description: S3 key for the Lambda function code ZIP file (e.g., lambda.zip)
  DatabaseHost:
    Type: String
    Description: PostgreSQL database host
  DatabaseUser:
    Type: String
    Description: PostgreSQL database user
  DatabasePassword:
    Type: String
    Description: PostgreSQL database password
    NoEcho: true
  GeminiApiKey:
    Type: String
    Description: API key for Gemini AI service
    NoEcho: true

Resources:
  # Lambda Execution Role
  GeneratorsLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole

  # Entry Info Generator Lambda Function
  EntryInfoGeneratorLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: EntryInfoGeneratorFunction
      Handler: entryInfoGeneratorLambda.handler
      Role: !GetAtt GeneratorsLambdaExecutionRole.Arn
      Code:
        S3Bucket: !Ref CodeS3Bucket
        S3Key: !Ref CodeS3Key
      Runtime: nodejs20.x
      Timeout: 900  # 15 minutes - AI processing can take time
      MemorySize: 1024  # 1GB - Need more memory for AI processing
      Environment:
        Variables:
          DB_HOST: !Ref DatabaseHost
          DB_USER: !Ref DatabaseUser
          DB_PASSWORD: !Ref DatabasePassword
          GEMINI_API_KEY: !Ref GeminiApiKey
      # Note: pg library is bundled in deployment package

  # Example Sentence Generator Lambda Function
  ExampleSentenceGeneratorLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: ExampleSentenceGeneratorFunction
      Handler: exampleSentenceGeneratorLambda.handler
      Role: !GetAtt GeneratorsLambdaExecutionRole.Arn
      Code:
        S3Bucket: !Ref CodeS3Bucket
        S3Key: !Ref CodeS3Key
      Runtime: nodejs20.x
      Timeout: 900  # 15 minutes - AI processing can take time
      MemorySize: 1024  # 1GB - Need more memory for AI processing
      Environment:
        Variables:
          DB_HOST: !Ref DatabaseHost
          DB_USER: !Ref DatabaseUser
          DB_PASSWORD: !Ref DatabasePassword
          GEMINI_API_KEY: !Ref GeminiApiKey
      # Note: pg library is bundled in deployment package


  # # EventBridge Rule for Entry Info Generator (runs every 30 minutes)
  # EntryInfoGeneratorScheduleRule:
  #   Type: AWS::Events::Rule
  #   Properties:
  #     Description: Triggers Entry Info Generator Lambda every 30 minutes
  #     ScheduleExpression: rate(30 minutes)
  #     State: ENABLED
  #     Targets:
  #       - Arn: !GetAtt EntryInfoGeneratorLambda.Arn
  #         Id: EntryInfoGeneratorLambdaTarget

  # # EventBridge Rule for Example Sentence Generator (runs every 45 minutes)
  # ExampleSentenceGeneratorScheduleRule:
  #   Type: AWS::Events::Rule
  #   Properties:
  #     Description: Triggers Example Sentence Generator Lambda every 45 minutes
  #     ScheduleExpression: rate(45 minutes)
  #     State: ENABLED
  #     Targets:
  #       - Arn: !GetAtt ExampleSentenceGeneratorLambda.Arn
  #         Id: ExampleSentenceGeneratorLambdaTarget

  # # Permission for EventBridge to invoke Entry Info Generator Lambda
  # EntryInfoGeneratorLambdaInvokePermission:
  #   Type: AWS::Lambda::Permission
  #   Properties:
  #     FunctionName: !Ref EntryInfoGeneratorLambda
  #     Action: lambda:InvokeFunction
  #     Principal: events.amazonaws.com
  #     SourceArn: !GetAtt EntryInfoGeneratorScheduleRule.Arn

  # # Permission for EventBridge to invoke Example Sentence Generator Lambda
  # ExampleSentenceGeneratorLambdaInvokePermission:
  #   Type: AWS::Lambda::Permission
  #   Properties:
  #     FunctionName: !Ref ExampleSentenceGeneratorLambda
  #     Action: lambda:InvokeFunction
  #     Principal: events.amazonaws.com
  #     SourceArn: !GetAtt ExampleSentenceGeneratorScheduleRule.Arn

Outputs:
  EntryInfoGeneratorLambdaArn:
    Description: ARN of the Entry Info Generator Lambda function
    Value: !GetAtt EntryInfoGeneratorLambda.Arn
    Export:
      Name: EntryInfoGeneratorLambdaArn

  ExampleSentenceGeneratorLambdaArn:
    Description: ARN of the Example Sentence Generator Lambda function
    Value: !GetAtt ExampleSentenceGeneratorLambda.Arn
    Export:
      Name: ExampleSentenceGeneratorLambdaArn

  # EntryInfoGeneratorScheduleRuleArn:
  #   Description: ARN of the Entry Info Generator EventBridge rule
  #   Value: !GetAtt EntryInfoGeneratorScheduleRule.Arn

  # ExampleSentenceGeneratorScheduleRuleArn:
  #   Description: ARN of the Example Sentence Generator EventBridge rule
  #   Value: !GetAtt ExampleSentenceGeneratorScheduleRule.Arn